language: python
python:
  - 2.7
install:
  # Download the Pypy depdencies
  - make -C src pypy
  # Install our other dependencies.
  - pip install -q -r src/requirements.pip
script:
  # Run our unit tests.
  - PYTHONPATH=src/pypy TRIFLEPATH=src coverage run --omit='src/pypy*,*site-packages*' src/tests.py
  # Ensure that we can build the binary (i.e. our source is RPython friendly).
  - python2 src/pypy/rpython/bin/rpython --batch src/main.py
after_success:
  coveralls
notifications:
  irc: "chat.freenode.net#trifle"